#!/bin/bash

script_temporario=$(mktemp /dev/shm/script_temporario.XXXXXX)

cat > $script_temporario <<\EOF
#!/bin/bash

export ZYPP_MEDIANETWORK=1

box(){
    local sentence="$1"
    local sentenceLenght=${#sentence}
    local horizontalSpacing=$(($sentenceLenght+2))

    local leftUpperCornerSymbol="╔"
    local rightUpperCornerSymbol="╗"
    local leftBottomCornerSymbol="╚"
    local rightBottomCornerSymbol="╝"
    local horizontalSymbol="═"
    local verticalSymbol="║"

    for line in $(seq 1 $horizontalSpacing)
    do
        local horizontalLine=$horizontalSymbol$horizontalLine
    done

    echo "$leftUpperCornerSymbol$horizontalLine$rightUpperCornerSymbol"
    echo "$verticalSymbol${horizontalLine//$horizontalSymbol/ }$verticalSymbol"
    echo "$verticalSymbol $sentence $verticalSymbol"
    echo "$verticalSymbol${horizontalLine//$horizontalSymbol/ }$verticalSymbol"
    echo "$leftBottomCornerSymbol$horizontalLine$rightBottomCornerSymbol"
}

atualizar_repositorios(){
    local comando="$1"
    box "Atualizando as informações dos repositórios"
    box "Executando \"$comando\""

    $comando
}

atualizar() {
    local comando="$1"

    box "Prosseguindo para a atualização dos pacotes..."

    box "Executando \"$comando\""
    
    box "Verifique o que será realizado antes de prosseguir!!"
    
    $comando
    retorno=$?
    
    if [ $retorno -ne 0 ]; then
        box "Algo deu errado!! Você pode tentar novamente."
    fi
    
    read -rep $'\nPresssione ENTER para sair...\n'
    pkcon get-updates
}

atualizar_repositorios "pkcon get-updates"
atualizar "/usr/bin/zypper dist-upgrade"
EOF

chmod +x $script_temporario

if [ -z $1 ]; then
    /usr/bin/xfce4-terminal --hide-menubar --hide-toolbar --zoom 1.5 --maximize -e "$0 0" -T "Instalar atualizações"
else
    /usr/bin/pkexec bash $script_temporario
    killall package-update-indicator
    nohup /usr/bin/package-update-indicator > /dev/null 2>&1 &

    # Sem esta espera, o comando acima
    # não possui tempo para se instanciar
    sleep 0.01
fi

rm -f $script_temporario
