#!/bin/bash

script_temporario="/tmp/atualizar_sistema"

if [ ! -z "$DISPLAY" ] && [ -z "$SSH_CONNECTION" ] && [ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ]; then
    RODAR_PRIVILEGIADO="/usr/bin/pkexec"
else
    RODAR_PRIVILEGIADO="/usr/bin/sudo"
fi

verifica_usuario_logado(){
    local usuario="$1"
    sessoes="$(loginctl list-sessions --no-legend | grep "$usuario" | awk '{print $1}' | xargs -I {} loginctl show-session -p Type --value {} | grep -E 'x11|wayland' | sort | uniq)"

    if [ ! -z "$sessoes" ]; then
        return
    fi

    false
}

script_atualizador(){
cat << 'EOF'
#!/bin/bash

export ZYPP_CURL2=1
export ZYPP_PCK_PRELOAD=1
export ZYPP_MEDIANETWORK=1

box(){
    local sentence="$1"
    local sentenceLenght=${#sentence}
    local horizontalSpacing=$(($sentenceLenght+2))

    local leftUpperCornerSymbol="╔"
    local rightUpperCornerSymbol="╗"
    local leftBottomCornerSymbol="╚"
    local rightBottomCornerSymbol="╝"
    local horizontalSymbol="═"
    local verticalSymbol="║"

    for line in $(seq 1 $horizontalSpacing)
    do
        local horizontalLine=$horizontalSymbol$horizontalLine
    done

    echo "$leftUpperCornerSymbol$horizontalLine$rightUpperCornerSymbol"
    echo "$verticalSymbol${horizontalLine//$horizontalSymbol/ }$verticalSymbol"
    echo "$verticalSymbol $sentence $verticalSymbol"
    echo "$verticalSymbol${horizontalLine//$horizontalSymbol/ }$verticalSymbol"
    echo "$leftBottomCornerSymbol$horizontalLine$rightBottomCornerSymbol"
}

atualizar_repositorios(){
    local comando="$1"
    box "Atualizando as informações dos repositórios"
    box "Executando \"$comando\""

    $comando
    sleep 1
}

encerrar_packagekit(){
    local sinalizador=$1
    local tempo=$2
    local rodadas=$(echo "scale=0; $tempo / 0.1" | bc)
    local contador=0

    while [ "$contador" -lt "$rodadas" ]; do
        if [ ! -f $sinalizador ]; then
            contador=$((contador + 1))
        fi

        pkill -f "packagekitd" -9
        sleep 0.1
    done
}

atualizar() {
    local comando="$1"

    box "Prosseguindo para a atualização dos pacotes..."

    box "Executando \"$comando\""

    box "Verifique o que será realizado antes de prosseguir!!"

    rm -f "$sinalizador"
    $comando
    retorno=$?

    if [ "$retorno" -ne 0 ]; then
        box "Algo deu errado!! Você pode tentar novamente."
    fi

    read -rep $'\nPressione ENTER para sair...\n'
}

sinalizador=$(mktemp)
atualizar_repositorios "pkcon get-updates"
encerrar_packagekit "$sinalizador" 3 &
atualizar "/usr/bin/zypper dist-upgrade --auto-agree-with-licenses --replacefiles"

rm -rf /var/tmp/rpm-tmp.*
rm -rf /var/tmp/zypp.*
EOF

    chmod +x $script_temporario
}


if [ -z $1 ] && [ "$RODAR_PRIVILEGIADO" = "/usr/bin/pkexec" ]; then
    /usr/bin/xfce4-terminal --hide-menubar --hide-toolbar --zoom 1.5 --maximize -e "$0 0" -T "Instalar atualizações" > /dev/null 2>&1 & disown

else
    script_atualizador > $script_temporario
    $RODAR_PRIVILEGIADO bash $script_temporario
    rm -f $script_temporario

    if verifica_usuario_logado "$USER"; then
        killall -q package-update-indicator -9
        while ! pgrep -f "/usr/bin/package-update-indicator" > /dev/null; do
            DISPLAY=:0 nohup /usr/bin/package-update-indicator > /dev/null 2>&1 &
            sleep 0.1
        done
    fi
fi
