#!/bin/bash

export verde="\033[1;32m"
export vermelho="\033[1;31m"
export amarelo="\033[1;33m"
export normal="\033[0m"

urls="$(curl -sL https://gradle.org/releases/ | grep 'https://services.gradle.org/distributions/gradle-' | grep -v 'all' | awk '{print $4}' | cut -f 2 -d '=')"

export ultima_versao=$(echo "$urls" | sort -V | tail -n 1 | grep -oP '(?<=gradle-)[0-9.]+(?=-bin\.zip)')
export dir_base="/opt"
export dir_instalacao="$dir_base/Gradle"
export binario="gradle"
export url_arquivo="https://services.gradle.org/distributions/gradle-$ultima_versao-bin.zip"
export pacote_java="java-25-openjdk-devel"

if [ -d "$dir_instalacao" ]; then
    versao_instalada=$(<"$dir_instalacao/version")

    if [ "$versao_instalada" == "$ultima_versao" ]; then
        echo "A versão mais recente já está instalada."
        echo "Versão atual: $versao_instalada"

        while [[ "$resposta_instalar_gradle" != [sSnN] ]]; do
            read -p "Deseja reinstalar? [s/n] " resposta_instalar_gradle < /dev/tty
        done

        if [[ "$resposta_instalar_gradle" == [nN] ]]; then
            exit 0
        fi
        mensagem_sucesso="reinstalado"
        mensagem_erro="reinstalar"
    else
        echo -e "\n${verde}Atualizando o Gradle da versão $versao_instalada para $ultima_versao...${normal}\n"
        mensagem_sucesso="atualizado"
        mensagem_erro="atualizar"
    fi
else
    echo -e "\n${verde}Instalando Gradle $ultima_versao...${normal}\n"
    mensagem_sucesso="instalado"
    mensagem_erro="instalar"
fi

if [ ! $(command -v java) ]; then
    echo -e "\n${vermelho}O comando \"java\" não foi encontrado.${normal}\n"

    while [[ "$resposta_instalar_java" != [sSnN] ]]; do
        read -p "Deseja instalar o OpenJDK 25? [s/n] " resposta_instalar_java < /dev/tty
    done

    if [[ "$resposta_instalar_java" == [nN] ]]; then
        echo -e "\n${amarelo}A instalação do Java será pulada. Entretando, você precisará instalar o Java posteriormente para utilizar corremente o Gradle.${normal}\n"
    else
        export instalar_java=true
    fi
fi

sudo -E -- bash -c '
    set -e
    if [ "$instalar_java" = true ]; then
         set -e
         barra_rotativa() {
             local barra_inicial="$1"

             if [ -z "$barra_inicial" ]; then
                 echo "|"
             elif [ "$barra_inicial" == "|" ]; then
                 echo "/"
             elif [ "$barra_inicial" == "/" ]; then
                 echo "-"
             elif [ "$barra_inicial" == "-" ]; then
                 echo "\\"
             else
                 echo "|"
             fi
         }

         echo -e "\n${verde}Procedendo para a instalação do OpenJDK 25...${normal}\n"

         while [ -s /run/zypp.pid ]; do
            barra="$(barra_rotativa "$barra")"
            echo -ne "O gerenciador de pacotes está ocupado por outro processo. Aguardando liberação... [$barra]\r"
            sleep 0.2
         done

         if [ ! -z "$barra" ]; then echo -ne "\033[2K"; fi

         echo -e "${amarelo}Atualizando a lista de pacotes...${normal}\n"
         repositorio="$(zypper info $pacote_java | grep -E "Reposit.*:" | sed -n "s/^.*: *//p")"

         zypper --gpg-auto-import-keys refresh -f -r "$repositorio"

         echo -e "\n${amarelo}Instalando o OpenJDK 25...${normal}\n"
         zypper -n install -y $pacote_java

         echo -e "\n${amarelo}Definindo a variável de ambiente JAVA_HOME...${normal}\n"
         echo "if type -q java ; set --export JAVA_HOME (dirname (dirname (readlink -f (which java)))) ; end" > /etc/fish/conf.d/java_home.fish
         set +e
    fi

    echo -e "\nBaixando Gradle $ultima_versao...\n"
    arquivo_baixado="/tmp/$(basename $url_arquivo)"
    wget -q --show-progress --read-timeout=5 --tries=0 -cO ${arquivo_baixado} ${url_arquivo}

    dir_raiz_zip=$(zipinfo -1 $arquivo_baixado | head -1)

    echo -e "\nExtraindo o arquivo baixado \"$arquivo_baixado\" para \"$dir_instalacao\"...\n"
    rm -rf "$dir_instalacao"
    unzip -o ${arquivo_baixado} -d $dir_base | pv -l >/dev/null
    mv $dir_base/$dir_raiz_zip/ $dir_instalacao
    echo "$ultima_versao" > $dir_instalacao/version
    rm -f /usr/local/bin/$binario
    ln -s $dir_instalacao/bin/$binario /usr/local/bin/$binario
    rm -f ${arquivo_baixado}
' < /dev/tty

echo -e "\n${verde}Instalação concluída. Você pode executar o comando \"gradle\" pelo terminal.${normal}\n"

if [ "$instalar_java" = true ]; then
    echo -e "${amarelo}Reinicie a sua sessão para que a variável de ambiente \"JAVA_HOME\" seja reconhecida por todas as aplicações.${normal}\n"
fi
