#!/bin/bash

export VERDE="\033[1;32m"
export VERMELHO="\033[1;31m"
export AMARELO="\033[1;33m"
export NORMAL="\033[0m"

export ULTIMA_VERSAO=$(curl -sL "https://www.postman.com/release-notes/postman-app/" | grep -oE "<title>.*</title>" | grep -o '[0-9]\+')
export NOME="Postman"
export BINARIO="postman"
export DIR_INSTALACAO_BASE="/opt"
export DIR_INSTALACAO="$DIR_INSTALACAO_BASE/Postman-$ULTIMA_VERSAO"
export URL_ARQUIVO="https://dl.pstmn.io/download/latest/linux?arch=64"

if [ -d /opt/$NOME-$ULTIMA_VERSAO ]; then
    echo "A versão mais recente já está instalada."
    echo "Versão atual: $ULTIMA_VERSAO"
    
    while [[ "$RESPOSTA_INSTALAR_NOVAMENTE" != [sSnN] ]]; do
        read -p "Deseja reinstalar? [s/n] " RESPOSTA_INSTALAR_NOVAMENTE < /dev/tty
    done

    if [[ "$RESPOSTA_INSTALAR_NOVAMENTE" == [nN] ]]; then
        exit 0
    fi
fi

echo -e "\n${VERDE}Instalando $NOME $ULTIMA_VERSAO...${NORMAL}\n"

set -e
sudo -E -- bash -c '
    echo -e "\nBaixando $NOME $ULTIMA_VERSAO...\n"
    ARQUIVO_BAIXADO="/tmp/postman.tar.gz"
    wget -q --show-progress --read-timeout=5 --tries=0 -cO ${ARQUIVO_BAIXADO} ${URL_ARQUIVO}
    rm -rf "$DIR_INSTALACAO"
    mkdir -p "$DIR_INSTALACAO"

    echo -e "\nExtraindo o arquivo baixado \"${ARQUIVO_BAIXADO}\" para \"$DIR_INSTALACAO\"...\n"
    pv ${ARQUIVO_BAIXADO} | tar -xz -C ${DIR_INSTALACAO} --strip-components=1
    rm -f /usr/local/bin/$BINARIO
    ln -s "$DIR_INSTALACAO/Postman" /usr/local/bin/$BINARIO
    rm -f ${ARQUIVO_BAIXADO}
    chown -R $SUDO_USER: "$DIR_INSTALACAO"

    echo -e "\nCriando atalho no menu...\n"
    printf "%s\n"                                         \
        "[Desktop Entry]"                                 \
        "Encoding=UTF-8"                                  \
        "Name=Postman"                                    \
        "Comment=Postman"                                 \
        "Exec=$BINARIO"                                   \
        "Icon=$DIR_INSTALACAO/app/icons/icon_128x128.png" \
        "Terminal=false"                                  \
        "Type=Application"                                \
        "Categories=Development;IDE;"                     \
        "StartupNotify=true" > /usr/share/applications/postman.desktop
'

echo -e "O $NOME $ULTIMA_VERSAO foi instalado com sucesso.\n"

echo -e "${VERDE}Você pode iniciar o $NOME a partir do menu ou executando o comando \"$BINARIO\" no terminal.${NORMAL}"