#!/bin/bash

export VERDE="\033[1;32m"
export VERMELHO="\033[1;31m"
export AMARELO="\033[1;33m"
export NORMAL="\033[0m"

export URL_ARQUIVO=$(curl -IsL https://api2.cursor.sh/updates/download/golden/linux-x64-rpm/cursor/ | grep -o 'location: https://[^[:space:]]*' | sed 's/location: //g')
export ULTIMA_VERSAO=$(basename $URL_ARQUIVO | grep -oP '(?<=cursor-)\d+\.\d+\.\d+(?=\.el[0-9]+\.x86_64\.rpm)')
export NOME="Cursor"
export BINARIO="cursor"
export DIR_INSTALACAO="/usr/share/cursor"

if [ $(command -v $BINARIO) ]; then
    VERSAO_INSTALADA=$(grep -oP '"version":\s*"\K[^"]+' $DIR_INSTALACAO/resources/app/package.json)

    if [ "$VERSAO_INSTALADA" == "$ULTIMA_VERSAO" ]; then
        echo -e "\n${AMARELO}A versão mais recente do $NOME já está instalada.${NORMAL}"
        echo -e "Versão atual: ${VERDE}$VERSAO_INSTALADA${NORMAL}\n"

        while [[ "$RESPOSTA_INSTALAR_NOVAMENTE" != [sSnN] ]]; do
            read -p "Deseja reinstalar? [s/n] " RESPOSTA_INSTALAR_NOVAMENTE < /dev/tty
        done

        if [[ "$RESPOSTA_INSTALAR_NOVAMENTE" == [nN] ]]; then
            exit 0
        fi
        MENSAGEM_SUCESSO="reinstalado"
        MENSAGEM_ERRO="reinstalar"
    else
        echo -e "\n${VERDE}Atualizando o $NOME da versão $VERSAO_INSTALADA para $ULTIMA_VERSAO...${NORMAL}\n"
        MENSAGEM_SUCESSO="atualizado"
        MENSAGEM_ERRO="atualizar"
    fi
else
    echo -e "\n${VERDE}Instalando o $NOME $ULTIMA_VERSAO...${NORMAL}\n"
    MENSAGEM_SUCESSO="instalado"
    MENSAGEM_ERRO="instalar"
fi

sudo -E -- bash -c '
    set -e
    echo -e "\n${VERDE}Baixando o $NOME $ULTIMA_VERSAO...${NORMAL}\n"
    ARQUIVO_BAIXADO="/tmp/$NOME.rpm"
    wget -q --show-progress --read-timeout=5 --tries=0 -cO ${ARQUIVO_BAIXADO} ${URL_ARQUIVO}

    echo -e "\n${VERDE}Instalando o $NOME $ULTIMA_VERSAO através do gerenciador de pacotes Zypper...${NORMAL}\n"
    zypper --non-interactive install --force --no-confirm --allow-unsigned-rpm ${ARQUIVO_BAIXADO}
    rm -f ${ARQUIVO_BAIXADO}
'

RETORNO=$?
if [ $RETORNO -eq 0 ]; then
    echo -e "\n${VERDE}O $NOME $ULTIMA_VERSAO foi $MENSAGEM_SUCESSO com sucesso.${NORMAL}\n"
    echo -e "${VERDE}Você pode iniciar o $NOME a partir do menu ou executando o comando \"$BINARIO\" no terminal.${NORMAL}"
else
    echo -e "\n${VERMELHO}Ocorreu um erro ao $MENSAGEM_ERRO o $NOME $ULTIMA_VERSAO.${NORMAL}\n"
    echo -e "${VERMELHO}Por favor, tente novamente.${NORMAL}"
fi