#!/bin/bash

export verde="\033[1;32m"
export vermelho="\033[1;31m"
export amarelo="\033[1;33m"
export normal="\033[0m"

versao=0
urls="$(curl -sL https://gradle.org/releases/ | grep 'https://services.gradle.org/distributions/gradle-' | grep -v 'all' | awk '{print $4}' | cut -f 2 -d '=')"

export versao=$(echo "$urls" | sort -V | tail -n 1 | grep -oP '(?<=gradle-)[0-9.]+(?=-bin\.zip)')

if [ -d /opt/Gradle/gradle-$versao ]; then
    echo "A versão mais recente já está instalada."
    echo "Versão atual: $versao"
    
    while [[ "$resposta_instalar_gradle" != [sSnN] ]]; do
        read -p "Deseja reinstalar? [s/n] " resposta_instalar_gradle < /dev/tty
    done

    if [[ "$resposta_instalar_gradle" == [nN] ]]; then
        exit 0
    fi
fi

echo -e "\n${verde}Instalando Gradle $versao...${normal}\n"

if [ ! $(command -v java) ]; then
    echo -e "\n${vermelho}O comando \"java\" não foi encontrado.${normal}\n"

    while [[ "$resposta_instalar_java" != [sSnN] ]]; do
        read -p "Deseja instalar o OpenJDK 25? [s/n] " resposta_instalar_java < /dev/tty
    done

    if [[ "$resposta_instalar_java" == [nN] ]]; then
        echo -e "\n${amarelo}A instalação do Java será pulada. Entretando, você precisará instalar o Java posteriormente para utilizar corremente o Gradle.${normal}\n"
    else
        export instalar_java=true
    fi
fi

export binario="gradle"
export dir_instalacao_base="/opt/Gradle"
export dir_instalacao="$dir_instalacao_base/gradle-$versao"
export dir_instalacao_simbolico="$dir_instalacao_base/gradle"
export url_arquivo="https://services.gradle.org/distributions/gradle-$versao-bin.zip"
export pacote_java="java-25-openjdk-devel"

set -e
sudo -E -- bash -c '
    if [ "$instalar_java" = true ]; then
         set -e
         barra_rotativa() {
             local barra_inicial="$1"

             if [ -z "$barra_inicial" ]; then
                 echo "|"
             elif [ "$barra_inicial" == "|" ]; then
                 echo "/"
             elif [ "$barra_inicial" == "/" ]; then
                 echo "-"
             elif [ "$barra_inicial" == "-" ]; then
                 echo "\\"
             else
                 echo "|"
             fi
         }

         echo -e "\n${verde}Procedendo para a instalação do OpenJDK 25...${normal}\n"

         while [ -s /run/zypp.pid ]; do
            barra="$(barra_rotativa "$barra")"
            echo -ne "O gerenciador de pacotes está ocupado por outro processo. Aguardando liberação... [$barra]\r"
            sleep 0.2
         done

         if [ ! -z "$barra" ]; then echo -ne "\033[2K"; fi

         echo -e "${amarelo}Atualizando a lista de pacotes...${normal}\n"
         repositorio="$(zypper info $pacote_java | grep -E "Reposit.*:" | sed -n "s/^.*: *//p")"

         zypper --gpg-auto-import-keys refresh -f -r "$repositorio"

         echo -e "\n${amarelo}Instalando o OpenJDK 25...${normal}\n"
         zypper -n install -y $pacote_java

         echo -e "\n${amarelo}Definindo a variável de ambiente JAVA_HOME...${normal}\n"
         echo "if type -q java ; set --export JAVA_HOME (dirname (dirname (readlink -f (which java)))) ; end" > /etc/fish/conf.d/java_home.fish
         set +e
    fi

    echo -e "\nBaixando Gradle $versao...\n"
    arquivo_baixado="/tmp/$(basename $url_arquivo)"
    wget -q --show-progress --read-timeout=5 --tries=0 -cO ${arquivo_baixado} ${url_arquivo}

    echo -e "\nExtraindo o arquivo baixado \"$arquivo_baixado\" para \"$dir_instalacao_base\"...\n"
    rm -rf "$dir_instalacao"
    mkdir -p "$dir_instalacao_base"
    unzip -o ${arquivo_baixado} -d /opt/Gradle/ | pv -l >/dev/null
    rm -f $dir_instalacao_simbolico
    ln -s $dir_instalacao $dir_instalacao_simbolico
    rm -f /usr/local/bin/$binario
    ln -s $dir_instalacao_simbolico/bin/$binario /usr/local/bin/$binario
    rm -f ${arquivo_baixado}
' < /dev/tty

echo -e "\n${verde}Instalação concluída. Você pode executar o comando \"gradle\" pelo terminal.${normal}\n"

if [ "$instalar_java" = true ]; then
    echo -e "${amarelo}Reinicie a sua sessão para que a variável de ambiente \"JAVA_HOME\" seja reconhecida por todas as aplicações.${normal}\n"
fi
